name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Make the screenshot interesting
        run: touch test.txt && open .
      - name: Capture a screenshot
        run: screencapture test.jpg
      - uses: actions/upload-artifact@v2
        with:
          path: test.jpg
